security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_CAISSIER:       [ROLE_USER, ROLE_CAISSIER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_CAISSIER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_CAISSIER, ROLE_SUPERADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login_check
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            http_basic : ~
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator        
    
        main:
            anonymous: true
            json_login:
                check_path: /api/login_check

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/creer ,            roles: ROLE_SUPERADMIN }   
        - { path: ^/api/partenaire,           roles: ROLE_SUPERADMIN }
        - { path: ^/api/compte,               roles: ROLE_SUPERADMIN }
        - { path: ^/api/compte,               roles: ROLE_ADMIN }
        - { path: ^/api/depot,                roles: ROLE_CAISSIER }
        - { path: ^/api/caissier,        roles: ROLE_SUPERADMIN }
        - { path: ^/api/user,                 roles: ROLE_ADMIN }
        - { path: ^/api/caissier,         roles: ROLE_ADMIN }
        - { path: ^/api/admin,        roles: ROLE_SUPERADMIN}

        #- { path: ^/api/user/,                roles: ROLE_ADMIN }  
        #- { path: ^/api,                      roles: ROLE_ADMIN}
         #- { path: ^/api/admin,        roles: ROLE_SUPERADMIN }
        #- { path: ^/api/user,        roles: ROLE_SUPERADMIN }
        #- { path: ^/api,                     roles: ROLE_USER }
        #- { path: ^/api/login,               roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api,                     roles: IS_AUTHENTICATED_FULLY }