vich_uploader:
    db_driver: orm

    mappings:
        utilisateurs:
            uri_prefix: /images/utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/utilisateurs'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
